import pandas as pd
import argparse
from pathlib import Path
import yaml

def filter_qc(qc_file_dir, nanostat_num_reads, nanostat_length_n50, pychopper_primers_found_pct, pychopper_inferred_strand_bias, genome_flagstat_mapped_pct):

    qc_df = pd.read_csv(qc_file_dir, sep="\t")

    qc_df["pychopper_total_reads"] = qc_df["pychopper_primers_found"] + qc_df["pychopper_rescue"] + qc_df["pychopper_unusable"]
    qc_df["pychopper_primers_found_pct"] = (qc_df["pychopper_primers_found"] / qc_df["pychopper_total_reads"]) * 100

    filtered_qc_df = qc_df[
    (qc_df["nanostats_num_reads"] > nanostat_num_reads) &
    (qc_df["nanostat_length_n50"] > nanostat_length_n50) &
    (qc_df["pychopper_primers_found_pct"] > pychopper_primers_found_pct) &
    (qc_df["pychopper_inferred_strand_bias"].between(1-pychopper_inferred_strand_bias, 1+pychopper_inferred_strand_bias)) &
    (qc_df["genome_flagstat_mapped_pct"] > genome_flagstat_mapped_pct)
    ]

    return filtered_qc_df


def create_isoquant_yaml(source_dir, df):
    file_paths = [
        f"{source_dir}/{row['run']}/c1ii-flagstat-genome-alignments/{row['barcode']}_minimap2_genome_aligned_sorted.bam"
        for _, row in df.iterrows()
    ]
    labels = [f"{row['run']}_{row['barcode']}" for _, row in df.iterrows()]

    yaml_data = [
        {"data format": "bam"},
        {
            "name": "USDA_RNA_seq",
            "long read files": file_paths,
            "labels": labels,
        },
    ]

    return yaml_data


def main():

    parser = argparse.ArgumentParser(
        description="Create qc filtered yaml file (for isoquant) and tsv file"
    )

    parser.add_argument(
        "-i",
        "--input",
        required=True,
        type=Path,
        help="input file with qc data generated by make_read_qc_report.smk"
    )

    parser.add_argument(
        "-s",
        "--source-dir",
        required=True,
        type=Path,
        help="source dir to where snakemake outputs are stored"
    )

    parser.add_argument(
        "-o",
        "--output",
        required=True,
        type=Path,
        help="Output directory."
    )

    parser.add_argument(
        "-r",
        "--nanostat-num-reads",
        required=True,
        type=float,
        help="minimum number of reads reported by nanostat per sample"
    )

    parser.add_argument(
        "-l",
        "--nanostat-length-n50",
        required=True,
        type=float,
        help="minimum number of N50 read length reported by nanostat per sample"
    )

    parser.add_argument(
        "-p",
        "--pychopper-primers-found-pct",
        required=True,
        type=float,
        help="minimum percentage of reads with primers identified by pychopper per sample"
    )

    parser.add_argument(
        "-b",
        "--pychopper-strand-bias",
        required=True,
        type=float,
        help="range of strand bias from 1.0 (caluclated by getting the ration of positive and negative strands)"
    )

    parser.add_argument(
        "-m",
        "--flagstat-mapped-pct",
        required=True,
        type=float,
        help="minimum mapping percentage of reads reported by flagstat"
    )

    args = parser.parse_args()

    output_dir = Path(args.output)
    input_file = Path(args.input)

    # Check input directory
    if not input_file.exists():
        raise FileNotFoundError(
            f"Input directory does not exist: {input_file}"
        )

    qc_filtered_df = filter_qc(
        input_file,
        nanostat_num_reads=args.nanostat_num_reads,
        nanostat_length_n50=args.nanostat_length_n50,
        pychopper_primers_found_pct=args.pychopper_primers_found_pct,
        pychopper_inferred_strand_bias=args.pychopper_strand_bias,
        genome_flagstat_mapped_pct=args.flagstat_mapped_pct
    )

    qc_output_file_tsv = output_dir / "qc_filtered_samples.tsv"
    qc_filtered_df.to_csv(qc_output_file_tsv, sep="\t", index=False)

    print(f"======== qc filtered tsv file saved to: {qc_output_file_tsv} ========")


    qc_output_file_yaml = output_dir / "qc_filtered_samples.yaml"
    yaml_data = create_isoquant_yaml(source_dir=args.source_dir, df=qc_filtered_df)
    with open(qc_output_file_yaml, "w") as f:
        yaml.dump(yaml_data, f, sort_keys=False, default_flow_style=False)

    print(f"======== qc filtered yaml file saved to: {qc_output_file_yaml} ========")

if __name__ == "__main__":
    main()