# usage: snakemake --profile profiles/slurm
executor: slurm
jobs: 24               # max concurrent jobs in slurm

resources:
  total_cpus: 192      # max cpu usage at any given time

# slurm-requeue: true    # this param was added after getting false erros from snakemake about node failing (althouh the job ran correctly and generated correct, compelete files)
retries: 1
latency-wait: 600      # seconds
rerun-incomplete: true
printshellcmds: true

default-resources:      # all rules so far has their on resource allocation
  mem_mb: 8000          # memory per task: 8G
  runtime: 900
  cpus_per_task: 12
  total_cpus: 12
  slurm_partition: "batch"
  slurm_account: "allusers"

set-resources:
  cat_reads:
    cpus_per_task: 8
    total_cpus: 8
    slurm_job_name: "fastcat_{wildcards.barcode}"
  nanostat_raw_reads:
    cpus_per_task: 8
    total_cpus: 8
    slurm_job_name: "nanostat_{wildcards.barcode}"
  pychopper_trim:
    cpus_per_task: 12
    total_cpus: 12
    pychopper_threads: 8
    pigz_threads: 4
    slurm_job_name: "pychopper_{wildcards.barcode}"
  align_to_transcriptome:
    cpus_per_task: 12
    total_cpus: 12
    minimap2_threads: 10
    samtools_threads: 2
  oarfish_quant_transcriptome_aligned:
    cpus_per_task: 12
    total_cpus: 12
    oarfish_threads: 12